version: '3.5'

services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.3
    volumes:
        - ./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /datos/sna/log/:/datos/sna/log/
     #   - /var/run/docker.sock:/var/run/docker.sock:ro
