filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: log
  paths:
    # - /datos/sna/log/rows.log
    - /datos/sna/log/*.log
   
  
  # Delete problems with multiline stacktrace errors
  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after

output.logstash:
  hosts: ["192.168.7.55:5044"]
  
# Para hacer debug de que lee correctamente el fichero de logs
#output.console:
#  pretty: true

# Para hacer debug de que llega al stack ELK (llega a ES siempre y cuando el docker de filebeat se conecte a la network del stack)
#output.elasticsearch:
#  hosts: ["http://192.168.7.55:9200"]
